import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, Github, Linkedin, Mail, MoveUpRight, Sparkles } from 'lucide-react'

const skills = ['React','TypeScript','JavaScript','Three.js','Tailwind CSS','AI / ML','Python','Git / GitHub']
const projects = [
  {number:'01',title:'GymPro',category:'Fitness Membership Platform',description:'A premium fitness membership experience designed around clear conversion paths, trainer guidance and health progress tracking.',url:'https://gympro-delta.vercel.app/',stack:['React','Responsive UI','Membership UX']},
  {number:'02',title:'WarehouseOS',category:'3D Operations Experience',description:'An immersive 3D warehouse interface that turns operational data into a living digital twin with fleet, inventory, sensor and shipment concepts.',url:'https://warehouse-two-iota.vercel.app/',stack:['React','Three.js','3D UI','Next.js']}
]

export default function App(){
 const [loaded,setLoaded]=useState(false),[active,setActive]=useState('React'),[sent,setSent]=useState(false),[menu,setMenu]=useState(false)
 useEffect(()=>{const t=setTimeout(()=>setLoaded(true),650);return()=>clearTimeout(t)},[])
 const mail=(subject='Project enquiry')=>{window.location.href='mailto:vangurijashuva@gmail.com?subject='+encodeURIComponent(subject)}
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const subject='Portfolio enquiry from '+(d.get('name')||'a visitor');const body=(d.get('message')||'')+'\n\nFrom: '+(d.get('name')||'')+'\nEmail: '+(d.get('email')||'');window.location.href='mailto:vangurijashuva@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);setSent(true);e.currentTarget.reset()}
 return <div className={'site '+(loaded?'is-loaded':'')}>
  <div className="loader"><div className="loader-inner"><span>JV</span><div className="loader-line"><i/></div><small>Loading portfolio</small></div></div>
  <header className="nav-shell"><a className="brand" href="#top"><span>JV</span><b>JASHUVA</b></a><button className="menu-button" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav className={menu?'nav open':'nav'}>{['About','Stack','Projects','Journey','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<button onClick={()=>mail('Let’s build something')}>Start a conversation <ArrowUpRight size={15}/></button></nav></header>
  <main id="top">
   <section className="hero section-frame"><div className="hero-copy"><div className="kicker"><span/> Frontend Developer / AI Interface Builder</div><h1>Interfaces with<br/><em>presence.</em></h1><p>I design and build polished digital products where strong frontend foundations meet AI, motion and thoughtful interaction.</p><div className="hero-actions"><a className="button button-dark" href="#projects">View selected work <MoveUpRight size={17}/></a><button className="button button-light" onClick={()=>mail('Hello Jashuva')}>Get in touch <Mail size={16}/></button></div><div className="hero-meta"><span><i/> Available for selected opportunities</span><span>India · Open to remote</span></div></div><div className="hero-portrait-wrap"><div className="portrait-frame"><img src="https://avatars.githubusercontent.com/u/166007699?v=4" alt="Jashuva Vanguri"/><div className="portrait-caption"><span>JASHUVA VANGURI</span><span>FRONTEND / AI</span></div></div><div className="hero-index">01 / 05</div><div className="hero-side-note">CRAFTED FOR THE WEB — 2026</div></div></section>
   <section id="about" className="section-frame section-space about"><div className="section-label">01 — About</div><div className="about-grid"><h2>Clean engineering.<br/><span>Distinctive direction.</span></h2><div><p className="lead">I’m Jashuva, a frontend developer focused on turning ideas into fast, responsive and memorable interfaces.</p><p>I care about hierarchy, typography, spacing, transitions, responsive behavior and the confidence of a well-finished product.</p><a className="text-link" href="#contact">Let’s make the next one <ArrowUpRight size={16}/></a></div></div></section>
   <section id="stack" className="section-frame section-space stack-section"><div className="section-label">02 — Stack</div><div className="stack-head"><h2>The tools behind<br/><span>the interface.</span></h2><p>Strong fundamentals first. AI and advanced interaction on top.</p></div><div className="skill-board"><div className="skill-list">{skills.map((s,i)=><button key={s} className={active===s?'skill active':'skill'} onMouseEnter={()=>setActive(s)} onFocus={()=>setActive(s)}><span>0{i+1}</span>{s}<ArrowUpRight size={15}/></button>)}</div><div className="skill-detail"><span className="detail-index">CURRENT FOCUS</span><strong>{active}</strong><p>{active==='Three.js'?'Building depth, 3D scenes and spatial product experiences.':active==='AI / ML'?'Using AI as a product capability, not a visual gimmick.':'Using '+active+' to create reliable, production-minded frontend experiences.'}</p><div className="detail-rule"><i/></div></div></div></section>
   <section id="projects" className="section-frame section-space projects-section"><div className="section-label">03 — Selected projects</div><div className="projects-intro"><h2>Work that earns<br/><span>the second look.</span></h2><p>Two recent builds — one conversion-focused, one spatial and experimental.</p></div><div className="project-stack">{projects.map((p,i)=><ProjectCard key={p.title} p={p} reverse={i%2===1}/>)}</div></section>
   <section id="journey" className="section-frame section-space journey-section"><div className="section-label">04 — Journey</div><div className="journey-grid"><h2>Learn fast.<br/><span>Build faster.</span></h2><div className="timeline">{[['FOUNDATIONS','HTML, CSS and JavaScript — the fundamentals that make everything else easier.'],['FRONTEND','React, responsive systems and component-driven product development.'],['BUILDING','Shipping real projects instead of collecting tutorials.'],['NOW','AI interfaces, 3D experiences and stronger product-level frontend craft.']].map((x,i)=><div className="timeline-item" key={x[0]}><span>0{i+1}</span><div><small>{x[0]}</small><p>{x[1]}</p></div></div>)}</div></div></section>
   <section id="contact" className="section-frame section-space contact"><div className="section-label">05 — Contact</div><div className="contact-grid"><div><h2>Have a good<br/><span>problem?</span></h2><p>Tell me what you’re building. If the idea is ambitious, I’m interested.</p><div className="contact-links"><a href="mailto:vangurijashuva@gmail.com"><Mail size={16}/> Email</a><a href="https://www.linkedin.com/in/jashuvavanguri/" target="_blank" rel="noreferrer"><Linkedin size={16}/> LinkedIn</a><a href="https://github.com/Jashuvav" target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a></div></div><form className="contact-form" onSubmit={submit}>{sent&&<div className="success"><Check size={15}/> Email draft opened — finish by pressing Send.</div>}<label><span>Name</span><input required name="name" placeholder="Your name"/></label><label><span>Email</span><input required type="email" name="email" placeholder="you@company.com"/></label><label><span>Message</span><textarea required name="message" placeholder="Tell me about the project…" rows={5}/></label><button className="button button-dark submit" type="submit">Send message <ArrowUpRight size={16}/></button></form></div></section>
  </main><footer className="section-frame footer"><span>© 2026 Jashuva Vanguri</span><span>Built with React · TypeScript · Vite</span><a href="#top"><Sparkles size={14}/> Back to top</a></footer>
 </div>
}
function ProjectCard({p,reverse}:{p:typeof projects[number],reverse:boolean}){return <article className={'project-card '+(reverse?'reverse':'')}><div className="project-copy"><span className="project-number">{p.number} / {p.category}</span><h3>{p.title}</h3><p>{p.description}</p><div className="project-tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div><a className="project-link" href={p.url} target="_blank" rel="noreferrer">Visit live project <ArrowUpRight size={16}/></a></div><a className="project-visual" href={p.url} target="_blank" rel="noreferrer"><div className="browser-top"><span/><span/><span/><small>{p.url.replace('https://','')}</small></div><div className="project-placeholder"><strong>{p.title}</strong><span>{p.category}</span></div><div className="visual-mark">VIEW PROJECT <ArrowUpRight size={15}/></div></a></article>}
